### PR TITLE
add/update states 000-009 from 7cf6be3

### PR DESCRIPTION
**Pull request by pdpinch**

### CODE REVIEW

**Comment by pdpinch** [comment]
@annagav in dashboard_states/dashboard_state_004_set_to_failed.png there's is some stray text ".here" in the message area. Is that for real?

**Comment by pdpinch** [comment]
The message changes in dashboard_states/dashboard_state_007_set_to_needs_upgrade.png from "You need to pay" to "You missed the payment deadline." I'd have to see the conditions to better know whether that was a good change. It may also be unrelated to this PR.

**Comment by pdpinch** [comment]
dashboard_states/dashboard_state_009_set_to_offered.png has a similar change in message to dashboard_states/dashboard_state_007_set_to_needs_upgrade.png

**Comment by annagav** [comment]
It changed in master as well. I am going to share a new master folder with you.

**Pull request closed without merging**
