### PR TITLE
add/update states 060-069 from 7fbaab0

### PR DESCRIPTION
**Pull request by pdpinch**
GitHub has a nice diff tool for images, but it can't handle more than 25 files at a time. This is the first of what I think will be 5 pull requests with the screenshot changes that derive from the PR at https://github.com/mitodl/micromasters/pull/3545/commits/7fbaab01872026d5542e68a7eefe4d9504ff5042

### CODE REVIEW

**Comment by pdpinch** [comment]
For some reason, I can't seem to comment on the files in the diff. 

Here are the files that appear to have changed in this PR:

1. https://github.com/pdpinch/micromasters-screenshots/blob/bc8d294b8232f7d4a69e53407f34621c04090ecc/dashboard_states/dashboard_state_063_create_exams_edx_%E2%9C%96_exam_%E2%9C%96_with_new_offering_can_schedule_more_exams.png

2. https://github.com/pdpinch/micromasters-screenshots/blob/bc8d294b8232f7d4a69e53407f34621c04090ecc/dashboard_states/dashboard_state_064_create_exams_edx_%E2%9C%96_exam_%E2%9C%96_with_new_offering_can_schedule_failed_one_exam.png

3. https://github.com/pdpinch/micromasters-screenshots/blob/bc8d294b8232f7d4a69e53407f34621c04090ecc/dashboard_states/dashboard_state_066_create_exams_edx_%E2%9C%96_exam_%E2%9C%96_with_new_offering_more_exams_failed_one_exam.png

4. https://github.com/pdpinch/micromasters-screenshots/blob/bc8d294b8232f7d4a69e53407f34621c04090ecc/dashboard_states/dashboard_state_067_create_exams_edx_%E2%9C%96_exam_%E2%9C%96_with_new_offering_more_exams.png

5. https://github.com/pdpinch/micromasters-screenshots/blob/bc8d294b8232f7d4a69e53407f34621c04090ecc/dashboard_states/dashboard_state_068_create_exams_edx_%E2%9C%96_exam_%E2%9C%96_with_new_offering_failed_one_exam.png

6. https://github.com/pdpinch/micromasters-screenshots/blob/bc8d294b8232f7d4a69e53407f34621c04090ecc/dashboard_states/dashboard_state_069_create_exams_edx_%E2%9C%96_exam_%E2%9C%96_with_new_offering.png

**Comment by pdpinch** [comment]
They all have in common the "You Paid for this course. Click the button to Enroll" message. This seems OK, but I'm not sure which course run the learner will be enrolled in when they click the button. 

It seems like we may be losing some information from the existing message about when the next run is starting.

**Comment by pdpinch** [comment]
@annagav is there a way to find out what happens when the learner clicks the Enroll button in these dashboard states? In particular, which course run will it try to enroll the learner in?

**Comment by annagav** [comment]
We would have to click on the button manually, for now. It should try to enroll in the currently enrollable course run.

**Comment by pdpinch** [comment]
For these, we can change the message to be the same as when the user hasn't paid, i.e. "You can enroll now/in the future"

**Pull request closed without merging**
